### PR TITLE
added images in features

### LINKED ISSUE #35: Update landing screenshots
The 3 screenshots of the landing page need to be updated so that they match the feature recently added (different encryption options).

The 3 new screenshots may be found [here](https://github.com/aliceandbob-io/files) and are named ```features_xxx_v2```.

### PR DESCRIPTION
**Pull request by megatank58**
Fixes #35

### CODE REVIEW

**Comment by aliceandbob-io** [comment]
Thanks @Megatank58, however the screenshots that need to be updated are the ones on this [page](https://github.com/aliceandbob-io/aliceandbob/blob/master/app/views/pages/_section_features.html.erb), which is the landing page of the website.

Can you please add a commit to your pull request with those changes? 🙏

**Review by aliceandbob-io — CHANGES_REQUESTED** [review]
Please update the screenshots on this [page](https://github.com/aliceandbob-io/aliceandbob/blob/master/app/views/pages/_section_features.html.erb) rather than on the README.md.

**Comment by megatank58** [comment]
Oh my bad sorry I'll do the changes

**Comment by megatank58** [comment]
I have updated the images and reverted readme

**Review by aliceandbob-io — APPROVED** [review]

**Comment by aliceandbob-io** [comment]
That's perfect! Thanks a lot. I'll close the PR and merge it so that it counts for your hacktoberfest 😉

**Comment by aliceandbob-io** [comment]
Closes #35

**Pull request merged**
